//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookk
    {
        public int id { get; set; }
        public string bookname { get; set; }
        public string author { get; set; }
        public string image { get; set; }
        public int price { get; set; }
    }
}
