//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mvcprojectEntities : DbContext
    {
        public mvcprojectEntities()
            : base("name=mvcprojectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminreg> adminregs { get; set; }
        public virtual DbSet<bookk> bookks { get; set; }
    
        public virtual int sp_bookadd(string na, string auth, string im, Nullable<int> pri)
        {
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var authParameter = auth != null ?
                new ObjectParameter("auth", auth) :
                new ObjectParameter("auth", typeof(string));
    
            var imParameter = im != null ?
                new ObjectParameter("im", im) :
                new ObjectParameter("im", typeof(string));
    
            var priParameter = pri.HasValue ?
                new ObjectParameter("pri", pri) :
                new ObjectParameter("pri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bookadd", naParameter, authParameter, imParameter, priParameter);
        }
    
        public virtual int sp_regadmin(string na, string addr, string em, string una, string pwd)
        {
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_regadmin", naParameter, addrParameter, emParameter, unaParameter, pwdParameter);
        }
    
        public virtual int sp_login(string una, string pwd, ObjectParameter status)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_login", unaParameter, pwdParameter, status);
        }
    
        public virtual int sp_bookkadd(string na, string auth, string im, Nullable<int> pri)
        {
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var authParameter = auth != null ?
                new ObjectParameter("auth", auth) :
                new ObjectParameter("auth", typeof(string));
    
            var imParameter = im != null ?
                new ObjectParameter("im", im) :
                new ObjectParameter("im", typeof(string));
    
            var priParameter = pri.HasValue ?
                new ObjectParameter("pri", pri) :
                new ObjectParameter("pri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_bookkadd", naParameter, authParameter, imParameter, priParameter);
        }
    
        public virtual ObjectResult<sp_selectall_Result> sp_selectall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectall_Result>("sp_selectall");
        }
    
        public virtual int sp_pwdchange(string uname, string oldpwd, string newpwd, ObjectParameter status)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var oldpwdParameter = oldpwd != null ?
                new ObjectParameter("oldpwd", oldpwd) :
                new ObjectParameter("oldpwd", typeof(string));
    
            var newpwdParameter = newpwd != null ?
                new ObjectParameter("newpwd", newpwd) :
                new ObjectParameter("newpwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_pwdchange", unameParameter, oldpwdParameter, newpwdParameter, status);
        }
    }
}
